In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf

tf.enable_eager_execution()

In [2]:
# In the tf.keras.layers package, layers are objects. To construct a layer,
# simply construct the object. Most layers take as a first argument the number
# of output dimensions / channels.
layer = tf.keras.layers.Dense(100)
# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [3]:
# To use a layer, simply call it.
layer(tf.zeros([10, 5]))

<tf.Tensor: id=29, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using `layer.variables` and trainable variables using
# `layer.trainable_variables`. In this case a fully-connected layer
# will have variables for weights and biases.
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.08643508, -0.265904  , -0.54709756,  0.35052925, -0.44231448,
         -0.17413402,  0.07372457,  0.3776644 ,  0.25508094,  0.4986711 ],
        [-0.5480121 , -0.528392  ,  0.14124465,  0.11416686,  0.347404  ,
          0.3074895 ,  0.01217866, -0.3308543 ,  0.17922813, -0.13920161],
        [ 0.30635136, -0.41935337,  0.48448783,  0.5448975 , -0.5215771 ,
         -0.3285563 , -0.4726534 ,  0.6015938 , -0.06870031,  0.3412711 ],
        [-0.26999477,  0.38305646,  0.48791522, -0.17812103,  0.4704457 ,
          0.01363224, -0.43215972, -0.45420647,  0.6320515 , -0.33142325],
        [ 0.32818598,  0.119591  ,  0.00684148, -0.00397146, -0.38117024,
          0.1952787 , -0.03807348, -0.54483575, -0.5649524 , -0.32297483]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [5]:
layer.trainable_variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.08643508, -0.265904  , -0.54709756,  0.35052925, -0.44231448,
         -0.17413402,  0.07372457,  0.3776644 ,  0.25508094,  0.4986711 ],
        [-0.5480121 , -0.528392  ,  0.14124465,  0.11416686,  0.347404  ,
          0.3074895 ,  0.01217866, -0.3308543 ,  0.17922813, -0.13920161],
        [ 0.30635136, -0.41935337,  0.48448783,  0.5448975 , -0.5215771 ,
         -0.3285563 , -0.4726534 ,  0.6015938 , -0.06870031,  0.3412711 ],
        [-0.26999477,  0.38305646,  0.48791522, -0.17812103,  0.4704457 ,
          0.01363224, -0.43215972, -0.45420647,  0.6320515 , -0.33142325],
        [ 0.32818598,  0.119591  ,  0.00684148, -0.00397146, -0.38117024,
          0.1952787 , -0.03807348, -0.54483575, -0.5649524 , -0.32297483]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [6]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.08643508, -0.265904  , -0.54709756,  0.35052925, -0.44231448,
         -0.17413402,  0.07372457,  0.3776644 ,  0.25508094,  0.4986711 ],
        [-0.5480121 , -0.528392  ,  0.14124465,  0.11416686,  0.347404  ,
          0.3074895 ,  0.01217866, -0.3308543 ,  0.17922813, -0.13920161],
        [ 0.30635136, -0.41935337,  0.48448783,  0.5448975 , -0.5215771 ,
         -0.3285563 , -0.4726534 ,  0.6015938 , -0.06870031,  0.3412711 ],
        [-0.26999477,  0.38305646,  0.48791522, -0.17812103,  0.4704457 ,
          0.01363224, -0.43215972, -0.45420647,  0.6320515 , -0.33142325],
        [ 0.32818598,  0.119591  ,  0.00684148, -0.00397146, -0.38117024,
          0.1952787 , -0.03807348, -0.54483575, -0.5649524 , -0.32297483]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [7]:
# ###  没明白
class MyDenseLayer(tf.keras.layers.Layer):
  def __init__(self, num_outputs):
    super(MyDenseLayer, self).__init__()
    self.num_outputs = num_outputs

  def build(self, input_shape):
    self.kernel = self.add_variable("kernel",
                                    shape=[int(input_shape[-1]),
                                           self.num_outputs])

  def call(self, input):
    return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.35174313,  0.32945484, -0.08482403, -0.38998234, -0.43166137,
        -0.1381034 ,  0.09853601, -0.2863308 ,  0.5548256 ,  0.24723828],
       [-0.275988  , -0.46704617,  0.24044538, -0.02796507, -0.37787655,
        -0.11522251, -0.5615468 ,  0.23866123,  0.22508973, -0.20404789],
       [-0.07282603,  0.34830618, -0.04086614,  0.03722864,  0.42867655,
         0.44665903, -0.2965546 , -0.54338044,  0.03326333,  0.37266892],
       [-0.607699  ,  0.23298568,  0.5201939 , -0.44425574, -0.33997494,
         0.15530044, -0.03601581,  0

In [8]:
class ResnetIdentityBlock(tf.keras.Model):   # 继承tf.keras.Model
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.trainable_variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization/gamma:0', 'resnet_identity_block/batch_normalization/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_1/gamma:0', 'resnet_identity_block/batch_normalization_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_2/gamma:0', 'resnet_identity_block/batch_normalization_2/beta:0']


In [9]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1)),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(2, 1,
                                                      padding='same'),
                               tf.keras.layers.BatchNormalization(),
                               tf.keras.layers.Conv2D(3, (1, 1)),
                               tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=513, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>